import BenchmarkChart from "../components/BenchmarkChart";
import PerQueryChart from "../components/PerQueryChart";
import SpeedupCallout from "../components/SpeedupCallout";
import CodeBlock from "../components/CodeBlock";
import { benchmarks } from "../lib/benchmarks";

const REPO = "https://github.com/vamzi/weft";

function SourceTag({ source }: { source: string }) {
  const pending = source === "pending";
  return (
    <span
      className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
        pending
          ? "bg-bg-subtle text-muted"
          : "bg-success/10 text-success"
      }`}
    >
      {pending ? "pending" : "measured"}
    </span>
  );
}

export default function PerformancePage() {
  const anyMeasured = benchmarks.engines.some((e) => e.total != null);
  return (
    <div className="weft-container py-14">
      {/* Header */}
      <div className="max-w-3xl">
        <span className="weft-eyebrow">ClickBench</span>
        <h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Performance</h1>
        <p className="mt-4 text-lg text-muted">
          A single, reproducible head-to-head: Weft against Sail, Apache Spark, and Spark with the
          Gluten/Velox native backend — same machine, same dataset, same Spark SQL. Every number
          here is generated by the harness in{" "}
          <a className="text-accent hover:underline" href={`${REPO}/tree/main/bench/clickbench/multi`}>
            bench/clickbench/multi
          </a>
          ; nothing is hand-entered.
        </p>
      </div>

      {!anyMeasured && (
        <div className="mt-8 rounded-weft border border-dashed border-hairline bg-bg-subtle p-4 text-sm text-muted">
          <strong className="text-body">Run in progress.</strong> The fresh benchmark is being
          measured on a dedicated {benchmarks.machine} per engine. Bars below are placeholders and
          fill in automatically when the run lands.
        </div>
      )}

      {/* Speedups */}
      <section className="mt-12">
        <h2 className="mb-4 text-lg font-semibold">Headline</h2>
        <SpeedupCallout />
      </section>

      {/* Total runtime */}
      <section className="mt-10">
        <BenchmarkChart
          engines={benchmarks.engines}
          title={
            benchmarks.commonCount
              ? `Total hot runtime — ${benchmarks.commonCount} queries all engines completed`
              : "Total hot runtime"
          }
        />
        {benchmarks.commonCount != null && benchmarks.commonCount < benchmarks.queryCount && (
          <p className="mt-2 text-xs text-muted">
            To compare fairly, the bars sum the {benchmarks.commonCount} of {benchmarks.queryCount}{" "}
            queries every engine executed — no engine is credited for skipping a hard query. Each
            engine's full total and the exact queries it couldn't run are in the table below.
          </p>
        )}
      </section>

      {/* Per-query */}
      <section className="mt-8">
        <PerQueryChart engines={benchmarks.engines} queryCount={benchmarks.queryCount} />
      </section>

      {/* Engine provenance table */}
      <section className="mt-12">
        <h2 className="mb-4 text-lg font-semibold">Engines & provenance</h2>
        <div className="overflow-hidden rounded-weft border border-hairline">
          <table className="w-full text-sm">
            <thead className="bg-bg-subtle text-left text-xs uppercase tracking-wide text-muted">
              <tr>
                <th className="px-4 py-2.5 font-medium">Engine</th>
                <th className="px-4 py-2.5 font-medium">Common-set total</th>
                <th className="px-4 py-2.5 font-medium">Full total</th>
                <th className="px-4 py-2.5 font-medium">Failed queries</th>
                <th className="px-4 py-2.5 font-medium">Status</th>
              </tr>
            </thead>
            <tbody>
              {benchmarks.engines.map((e) => (
                <tr key={e.key} className="border-t border-hairline">
                  <td className="px-4 py-2.5 font-medium">
                    {e.name}
                    {e.highlight && <span className="ml-2 text-xs text-accent">ours</span>}
                  </td>
                  <td className="px-4 py-2.5 tabular-nums font-semibold">
                    {e.total != null ? `${e.total.toFixed(2)}s` : "—"}
                  </td>
                  <td className="px-4 py-2.5 tabular-nums text-muted">
                    {e.totalAll != null ? `${e.totalAll.toFixed(2)}s` : "—"}
                  </td>
                  <td className="px-4 py-2.5 tabular-nums">
                    {e.failures ? (
                      <span title={`Q${(e.failedQueries ?? []).join(", Q")}`}>
                        {e.failures}{" "}
                        <span className="text-xs text-muted">
                          (Q{(e.failedQueries ?? []).join(", Q")})
                        </span>
                      </span>
                    ) : e.failures === 0 ? (
                      "0"
                    ) : (
                      "—"
                    )}
                  </td>
                  <td className="px-4 py-2.5">
                    <SourceTag source={e.source} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="mt-3 text-xs text-muted">
          A failed query is one an engine could not execute; it is counted as a gap, never silently
          dropped or excluded from the total comparison.
        </p>
      </section>

      {/* Methodology */}
      <section className="mt-12 grid gap-8 lg:grid-cols-2">
        <div>
          <h2 className="mb-3 text-lg font-semibold">Methodology</h2>
          <ul className="space-y-2.5 text-sm text-muted">
            <li>
              <strong className="text-body">Dataset.</strong> {benchmarks.dataset} — downloaded
              once, shared by every engine.
            </li>
            <li>
              <strong className="text-body">Hardware.</strong> Each engine runs on its own
              dedicated {benchmarks.machine} (16 vCPU / 32 GiB) — ClickBench's own per-engine
              methodology.
            </li>
            <li>
              <strong className="text-body">Queries.</strong> The 43 upstream ClickBench queries in
              Spark SQL, byte-for-byte identical across all four engines.
            </li>
            <li>
              <strong className="text-body">Transport.</strong> {benchmarks.method}.
            </li>
            <li>
              <strong className="text-body">Fairness.</strong> One stock PySpark client drives every
              engine; tuning is limited to documented defaults (shuffle partitions = vCPUs,
              off-heap sized for Gluten). This is a fair first run, not a tuning war.
            </li>
          </ul>
        </div>
        <div>
          <h2 className="mb-3 text-lg font-semibold">Reproduce it</h2>
          <CodeBlock
            lines={[
              { text: "# on a fresh c6a.4xlarge (Ubuntu 24.04)", comment: true },
              { text: "git clone https://github.com/vamzi/weft && cd weft" },
              { text: "" },
              { text: "# deps + JDK + Rust + all four engines", comment: true },
              { text: "bash bench/clickbench/multi/bootstrap.sh" },
              { text: "" },
              { text: "# download 14.78 GB once, run 43×3×4", comment: true },
              { text: "bash bench/clickbench/multi/run-all.sh" },
              { text: "" },
              { text: "# emit the chart data on this page", comment: true },
              { text: "python3 bench/clickbench/multi/to-site.py" },
            ]}
          />
          <p className="mt-3 text-xs text-muted">
            {benchmarks.runDate ? `Last run: ${benchmarks.runDate}.` : "Awaiting first published run."}{" "}
            Harness & raw scripts:{" "}
            <a className="text-accent hover:underline" href={`${REPO}/tree/main/bench/clickbench/multi`}>
              bench/clickbench/multi
            </a>
            .
          </p>
        </div>
      </section>
    </div>
  );
}
