//! Parser for Spark's `.sql.out` golden files.
//!
//! Format (generated by Spark's `SQLQueryTestSuite`):
//!
//! ```text
//! -- Automatically generated by SQLQueryTestSuite
//! -- !query
//! <sql, possibly multi-line>
//! -- !query schema
//! <one line: struct<...>>
//! -- !query output
//! <zero or more lines: rows, or an error rendering>
//! <blank line(s)>
//! -- !query
//! ...
//! ```
//!
//! We split on the `-- !query` / `-- !query schema` / `-- !query output` marker lines. The
//! leading header comment and inter-block blank padding are ignored.

use crate::GoldenBlock;

const Q: &str = "-- !query";
const SCHEMA: &str = "-- !query schema";
const OUTPUT: &str = "-- !query output";

/// Parse the full text of a `.sql.out` file into its ordered blocks.
pub fn parse(text: &str) -> Vec<GoldenBlock> {
    let lines: Vec<&str> = text.lines().collect();
    let mut blocks = Vec::new();
    let mut i = 0;

    while i < lines.len() {
        if lines[i].trim_end() != Q {
            i += 1;
            continue;
        }
        // Collect SQL lines until the schema marker.
        i += 1;
        let sql = take_until(&lines, &mut i, SCHEMA);
        // The schema marker line itself.
        if i < lines.len() && lines[i].trim_end() == SCHEMA {
            i += 1;
        }
        let schema = take_until(&lines, &mut i, OUTPUT);
        // The output marker line.
        if i < lines.len() && lines[i].trim_end() == OUTPUT {
            i += 1;
        }
        // Output runs until the next `-- !query` (exactly, not the schema/output variants).
        let output = take_until_block_end(&lines, &mut i);

        blocks.push(GoldenBlock {
            sql: sql.trim_matches('\n').to_string(),
            schema: schema.trim().to_string(),
            output: output.trim_matches('\n').to_string(),
        });
    }
    blocks
}

/// Join lines (advancing `i`) until a line whose trimmed form equals `marker`.
fn take_until(lines: &[&str], i: &mut usize, marker: &str) -> String {
    let start = *i;
    while *i < lines.len() && lines[*i].trim_end() != marker {
        *i += 1;
    }
    lines[start..*i].join("\n")
}

/// Join output lines until the next block start (`-- !query` but NOT `-- !query schema`
/// / `-- !query output`, which only appear *inside* a block).
fn take_until_block_end(lines: &[&str], i: &mut usize) -> String {
    let start = *i;
    while *i < lines.len() {
        let t = lines[*i].trim_end();
        if t == Q {
            break;
        }
        *i += 1;
    }
    lines[start..*i].join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_rows_schema_and_error_blocks() {
        let text = "\
-- Automatically generated by SQLQueryTestSuite
-- !query
CREATE OR REPLACE TEMPORARY VIEW t AS SELECT 1 a
-- !query schema
struct<>
-- !query output



-- !query
SELECT COUNT(a), COUNT(b) FROM t GROUP BY a
-- !query schema
struct<count(a):bigint,count(b):bigint>
-- !query output
0\t1
2\t2


-- !query
SELECT a FROM t GROUP BY b
-- !query schema
struct<>
-- !query output
org.apache.spark.sql.catalyst.ExtendedAnalysisException
{
  \"errorClass\" : \"MISSING_AGGREGATION\"
}
";
        let blocks = parse(text);
        assert_eq!(blocks.len(), 3);

        // DDL: empty schema and output.
        assert!(blocks[0].sql.starts_with("CREATE OR REPLACE"));
        assert_eq!(blocks[0].schema, "struct<>");
        assert_eq!(blocks[0].output, "");
        assert!(!blocks[0].expects_error());

        // Rows.
        assert_eq!(blocks[1].schema, "struct<count(a):bigint,count(b):bigint>");
        assert_eq!(blocks[1].output, "0\t1\n2\t2");
        assert!(!blocks[1].expects_error());

        // Error.
        assert!(blocks[2].expects_error());
        assert!(blocks[2].output.contains("MISSING_AGGREGATION"));
    }

    #[test]
    fn multiline_sql_is_preserved() {
        let text = "\
-- !query
SELECT *
FROM t
WHERE x > 1
-- !query schema
struct<x:int>
-- !query output
2
";
        let blocks = parse(text);
        assert_eq!(blocks.len(), 1);
        assert_eq!(blocks[0].sql, "SELECT *\nFROM t\nWHERE x > 1");
        assert_eq!(blocks[0].output, "2");
    }
}
